// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr2LAYVB-JZnOdLQmGuYfjCW_oCe5MwbE',
    appId: '1:54938574355:web:8f939a97c99ed7f1a0e9e6',
    messagingSenderId: '54938574355',
    projectId: 'ggr-farm',
    authDomain: 'ggr-farm.firebaseapp.com',
    databaseURL: 'https://ggr-farm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ggr-farm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0_QaJTioqhK1_gb_cSUfrBOUD9TxbK9I',
    appId: '1:54938574355:android:d9d2a9b516447bb4a0e9e6',
    messagingSenderId: '54938574355',
    projectId: 'ggr-farm',
    databaseURL: 'https://ggr-farm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ggr-farm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB42Q76Q9zoa8BM4Nf7WY9M3KR-FnqHQVQ',
    appId: '1:54938574355:ios:45d60f9c873f825ea0e9e6',
    messagingSenderId: '54938574355',
    projectId: 'ggr-farm',
    databaseURL: 'https://ggr-farm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ggr-farm.appspot.com',
    androidClientId: '54938574355-8nfqhjki8706h7j44fbflff7e91hbsv1.apps.googleusercontent.com',
    iosClientId: '54938574355-0kcmgca37nc33f7df41betceegc1eik2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ggrAlpha11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB42Q76Q9zoa8BM4Nf7WY9M3KR-FnqHQVQ',
    appId: '1:54938574355:ios:45d60f9c873f825ea0e9e6',
    messagingSenderId: '54938574355',
    projectId: 'ggr-farm',
    databaseURL: 'https://ggr-farm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ggr-farm.appspot.com',
    androidClientId: '54938574355-8nfqhjki8706h7j44fbflff7e91hbsv1.apps.googleusercontent.com',
    iosClientId: '54938574355-0kcmgca37nc33f7df41betceegc1eik2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ggrAlpha11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr2LAYVB-JZnOdLQmGuYfjCW_oCe5MwbE',
    appId: '1:54938574355:web:4cc48b099b27c204a0e9e6',
    messagingSenderId: '54938574355',
    projectId: 'ggr-farm',
    authDomain: 'ggr-farm.firebaseapp.com',
    databaseURL: 'https://ggr-farm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ggr-farm.appspot.com',
  );
}
